# Generated by Django 3.2.25 on 2025-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinfo',
            name='activation_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='findmy_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='housing_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='model_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='region_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='region_info_human_readable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deviceinfo',
            name='storage_capacity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
